language: node_js
node_js:
  - "node"
  - "lts/*"
notifications:
  email: false
script:
  - npm --prefix packages/lib run lint
  - npm --prefix packages/lib run typescript
  - npm --prefix packages/lib run test
